import { createClient } from "@/lib/supabase/server";
import { createProduct, deleteProduct } from "../actions";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: store } = await supabase.from("stores").select("id, name").eq("owner_id", user!.id).maybeSingle();
  const { data: products } = store ? await supabase.from("products").select("id, name, description, price_usd, is_active").eq("store_id", store.id).order("created_at", { ascending: false }) : { data: [] };
  const params = await searchParams;
  return <main className="mx-auto max-w-6xl space-y-8 px-6 py-10"><div><p className="text-sm text-slate-500">Catálogo</p><h1 className="text-3xl font-semibold">Productos</h1></div>{params.error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{params.error}</p> : null}{!store ? <p className="rounded-xl border bg-white p-6">Crea tu tienda en el resumen antes de agregar productos.</p> : <div className="grid gap-8 lg:grid-cols-[340px_1fr]"><section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Nuevo producto</h2><form action={createProduct} className="mt-5 grid gap-4"><input type="hidden" name="store_id" value={store.id} /><input name="name" required maxLength={160} placeholder="Nombre" className="h-11 rounded-lg border px-3" /><textarea name="description" maxLength={1000} placeholder="Descripción (opcional)" className="min-h-24 rounded-lg border p-3" /><label className="text-sm font-medium">Precio en USD<input name="price_usd" required type="number" min="0.01" step="0.01" className="mt-1 h-11 w-full rounded-lg border px-3" /></label><button className="rounded-lg bg-emerald-600 px-4 py-3 font-semibold text-white">Agregar producto</button></form></section><section className="space-y-3">{products?.length ? products.map((product) => <article key={product.id} className="flex items-center justify-between rounded-xl border bg-white p-5"><div><h2 className="font-semibold">{product.name}</h2><p className="text-sm text-slate-500">{product.description || "Sin descripción"}</p><p className="mt-2 font-medium text-emerald-700">${Number(product.price_usd).toFixed(2)}</p></div><form action={deleteProduct}><input type="hidden" name="product_id" value={product.id} /><button className="text-sm text-red-600 hover:underline">Eliminar</button></form></article>) : <p className="rounded-xl border bg-white p-6 text-slate-500">Todavía no tienes productos.</p>}</section></div>}</main>;
}
