import { createClient } from "@/lib/supabase/server";
import { createStore, refreshAutomaticRate, updateStore } from "../actions";
import { ExchangeRateToggle } from "@/components/exchange-rate-toggle";

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: store } = await supabase.from("stores").select("*").eq("owner_id", user!.id).maybeSingle();
  const params = await searchParams;
 return <main className="mx-auto max-w-6xl space-y-8 px-6 py-10"><div><p className="text-sm text-slate-500">Panel del comerciante</p><h1 className="text-3xl font-semibold">Resumen de tu negocio</h1></div>{params.error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{params.error}</p> : null}{!store ? <section className="max-w-xl rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Crea tu tienda</h2><p className="mt-2 text-sm text-slate-600">Configura el nombre público y el enlace de tu vitrina.</p><form action={createStore} className="mt-5 grid gap-4"><input name="name" required placeholder="Nombre del negocio" className="h-11 rounded-lg border px-3" /><input name="slug" required placeholder="mi-tienda" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="h-11 rounded-lg border px-3" /><button className="rounded-lg bg-emerald-600 px-4 py-3 font-semibold text-white">Crear tienda</button></form></section> : <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Configuración de pagos</h2><p className="mt-1 text-sm text-slate-500">{store.name} · /{store.slug}</p><form action={updateStore} className="mt-6 grid max-w-2xl gap-4"><input type="hidden" name="name" value={store.name} /><input type="hidden" name="slug" value={store.slug} /><label className="text-sm font-medium">Correo Zelle<input name="zelle_email" defaultValue={store.zelle_email ?? ""} placeholder="pagos@negocio.com" className="mt-1 h-11 w-full rounded-lg border px-3" /></label><label className="text-sm font-medium">Teléfono Pago Móvil<input name="pago_movil_phone" defaultValue={store.pago_movil_phone ?? ""} placeholder="0412-1234567" className="mt-1 h-11 w-full rounded-lg border px-3" /></label><label className="text-sm font-medium">Banco<input name="pago_movil_bank" defaultValue={store.pago_movil_bank ?? ""} placeholder="Banco de Venezuela" className="mt-1 h-11 w-full rounded-lg border px-3" /></label><label className="text-sm font-medium">Cédula / RIF<input name="pago_movil_id" defaultValue={store.pago_movil_id ?? ""} placeholder="V-12345678" className="mt-1 h-11 w-full rounded-lg border px-3" /></label><div className="border-t pt-4"><p className="mb-3 text-sm font-medium">Tasa de cambio</p><ExchangeRateToggle automatic={store.exchange_rate_mode === "automatic"} /><p className="mt-2 text-xs text-slate-500">Tasa BCV simulada actual: {store.current_exchange_rate ?? "sin actualizar"}</p></div><div className="flex flex-wrap gap-3"><button className="rounded-lg bg-emerald-600 px-4 py-3 font-semibold text-white">Guardar configuración</button><button formAction={refreshAutomaticRate} className="rounded-lg border px-4 py-3 font-semibold">Actualizar tasa BCV</button></div></form></section>}</main>;
}
